### ISSUE TITLE
Boot with QEMU? [iMac i386]

### ISSUE THREAD

**Issue by Justiniscoding** [Amog-OS/AmogOS#114]
Can you boot AmogOS with [QEMU](https://www.qemu.org/)? After downloading [AmogOS-1.4.1-x86_64.iso](https://github.com/Amog-OS/AmogOS/releases/download/x64-1.4.1/AmogOS-1.4.1-x86_64.iso) from your website, I tried to use QEMU to run it on my computer (I am on MacOS). I ran the following command in the terminal and I got no results, it showed no GUI and gave me no errors:
```sh
qemu-system-x86_64 -boot d -cdrom AmogOS-1.4.1-x86_64.iso -m 1024
```

How can I boot AmogOS with QEMU?

**Comment by mobilegmYT** [comment]
Try this one? https://github.com/Amog-OS/AmogOS/releases/download/x64-1.4.2/amogos-x86_64.iso

**Comment by HelenaMKG** [comment]
Please repeat what you just tried to do with v1.4.2, if you are not successful we will look into resolving the issue.

**Comment by Justiniscoding** [comment]
Is their a torrent for v1.4.2 so I can download it faster?

**Comment by Justiniscoding** [comment]
Is their a minimum requirement of RAM I need to use AmogOS in qemu?

**Comment by Justiniscoding** [comment]
Running it with the new installer produces the same result as the other installer

**Comment by Justiniscoding** [comment]
there is no GUI and there are not any error logs

**Comment by HelenaMKG** [comment]
Are you on an Apple Silicon ARM or Intel x86 Mac?

**Comment by HelenaMKG** [comment]
**Version 1.4.2 works on x86_64 Debian Testing's QEMU** when I give it 2GB of RAM. The issue you are experiencing may be an issue with QEMU on certain architectures and not an issue with AmogOS. For now, I recommend you use the ARM/RPi versions of AmogOS.

If you want to delve into this issue further then I recommend you try booting [Slax Linux](https://www.slax.org/) since we use the same boot and imaging toolchain as them. If the issue doesn't turn up there, then maybe we have screwed something up. Additionally, if you're feeling like it, you may want to [build bleeding edge QEMU](https://gitlab.com/qemu-project/qemu).

We really cannot do anything to actively debug this issue, because I'm pretty sure no one on the team has Mac hardware, and if they do I don't even know if they hardware is strong enough to support emulation. As far as I am concerned, this is a QEMU bug and not an AmogOS bug. I'm deeply sorry for your problem, though.

**Comment by Justiniscoding** [comment]
> Are you on an Apple Silicon ARM or Intel x86 Mac?
I am on an intel x86 mac

**Comment by Justiniscoding** [comment]
The problem may be the fact that I am using an older iMac, so I cannot update to the latest macOS version. However, when I installed qemu with macports I got no errors

**Comment by HelenaMKG** [comment]
Please, make sure that all the dependencies for QEMU are correctly built and installed. Additionally, I think the hardware support may just not be there. I recommend you emulate ARM64 and try running the RPI version, however.

**This issue needs input:**

- From people on newer macs.
- From people on older iMac models.
- From people who know about QEMU limitations.

**Comment by Justiniscoding** [comment]
Whenever I tried using qemu after installing with macports, it always gave me a blank result. I am currently installing it with homebrew to see if it will work

**Comment by mobilegmYT** [comment]
Closing since inactive.
